FROM python:3.12-slim

ENV SERVICE_NAME=Quaks
ENV SERVICE_VERSION=1.5.33
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV HOST=0.0.0.0
ENV PORT=8000
ENV WORKERS=1

WORKDIR /agent-lab

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY ../../pyproject.toml ../../uv.lock /agent-lab/
RUN apt update -q && apt install -yq build-essential \
    && uv sync --frozen --no-dev --no-install-project \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && groupadd -r agent-lab \
    && useradd -r -g agent-lab -d /agent-lab agent-lab \
    && chown -R agent-lab:agent-lab /agent-lab

USER agent-lab
COPY ../../app /agent-lab/app/
COPY ../../config-docker.yml /agent-lab/

CMD ["/bin/bash", "-x", "-c", "/agent-lab/.venv/bin/python -m uvicorn app.main:app --host ${HOST} --port ${PORT} --workers ${WORKERS}"]
