api_base_url: "http://test"
cdp_url: "http://localhost:19222"
auth:
  enabled: "True"
  url: "http://localhost:18080"
  realm: "test-realm"
  client_id: "test-client"
  client_secret: "test-secret"
broker:
  url: "redis://localhost:16379/0"
db:
  url: "postgresql://postgres:postgres@localhost:15432/agent_lab"
  vectors: "postgresql://postgres:postgres@localhost:15432/agent_lab_vectors"
  checkpoints: "postgresql://postgres:postgres@localhost:15432/agent_lab_checkpoints"
vault:
  url: "http://localhost:18200"
  token: "dev-only-token"
