
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-lab.fullname" . }}
  labels:
    {{- include "agent-lab.labels" . | nindent 4 }}
data:
  OLLAMA_ENDPOINT: "{{ .Values.config.ollama_endpoint }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.telemetry_endpoint }}"
